### ISSUE TITLE
Print toggles view and summary

### ISSUE THREAD

**Issue by nagibyro** [skluck/skill-survey#30]
## Detail
When you hit print it toggles summary and viewer. Which makes the behaviour of print unexpected if you were looking at summary and already had toggled it on and then went to print you wont get the summary in the printed pdf. (same with viewer).

## Expected
When you hit print it should make sure summary and viewer are toggled on but don't turn them off if already toggled on.

**Comment by skluck** [comment]
Fixed in 12104d9
